# Generated by Django 5.0.1 on 2024-12-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_founder_investor_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='investment_amount',
        ),
        migrations.AddField(
            model_name='investor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='investor_images/'),
        ),
        migrations.AddField(
            model_name='investor',
            name='investment_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='startup_name',
            field=models.CharField(default=10000, max_length=200),
            preserve_default=False,
        ),
    ]
