# Generated by Django 5.0.1 on 2024-12-22 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_investor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_requests', to='myapp.founder')),
            ],
        ),
    ]
